apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: default  # Change to your desired namespace if needed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
