apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30003  # Choose a port in the NodePort range (30000-32767)
  type: NodePort
