eureka:
  instance:
    hostname: discovery-service   # This should match the service name in Kubernetes
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
