spring:
  application:
    name: account-service
  data:
    mongodb:
      host: mydb
      port: 27017
      database: mydatabase
  main:
    allow-bean-definition-overriding: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#
#ribbon:
#  eureka:
#    enabled: true
