name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main  # Specify the branch to trigger the action on (e.g., 'main' or 'dev')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://<region>-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t <region>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/<repo-name>/<image-name>:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push <region>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/<repo-name>/<image-name>:${{ github.sha }}
